### ISSUE TITLE
[Feature Request] New Shortcut - Open File Explorer Context Menu

### ISSUE THREAD

**Issue by FelipeRearden** [1C0D/obsidian-explorer-shortcuts#1]
Hello @1C0D !!!!

What an amazing idea ! You always have the best plugins to make our Obsidian life easier. 

My FR is simple to explain: would be possible to add a shortcut to open the **File Explorer Context Menu**?

By File Explorer Context Menu I mean the menu that opens when you use the mouse right click inside a file or folder in the File Explorer 

📸
![IMG_1157](https://github.com/1C0D/obsidian-explorer-shortcuts/assets/85180696/ca699fc7-fa0b-44b0-b46e-369f8773bf50)

<hr>

I hope you like my idea 🙏 🙏 🙏

Let me know if you need more information!

I wish you a fantastic day ☀️

**Comment by 1C0D** [comment]
I don't understand why don't just use the right click ?

**Comment by FelipeRearden** [comment]
> I don't understand why don't just use the right click ?

Because wanna navigate the File Explorer 100% of the time with the keyboard :)

All my workflow in Obsidian workspace is using the keyboard the only piece of this puzzle that is missing is the File Explorer :)

That’s why I am so excited about this plugin because finally I could use the File Explorer without the mouse and the only operation that is missing is the context menu 🙏

**Comment by 1C0D** [comment]
This one is a little bit weird. Replacing right click by a shortcut isn't super logical. And more, you don't have this behavior anywhere else. So it doesn't make sens for most users. It's too specific to be introduced. But I keep this in mind.
